### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by Daniel-Baranowski-BJSS** [JonPSmith/AspNetReactSamples#3]
Is there a way to enable server side rendering for ReactWebPack.Core example ?

**Comment by JonPSmith** [comment]
Hi @Daniel-Baranowski-BJSS,

I did look at this when I wrote the article, but I didn't follow it up. [ReactJs.NET docs](http://reactjs.net/) says that you can use ReactJs.NET with WebPack. Therefore you would start with the ReactWebPack.Core example in my sample and add ReactJs.NET to handle the server-side rendering.

There is a useful page about [ReactJs.NET WebPack](http://reactjs.net/guides/webpack.html) which talks about how to do it. It also points to an [ReactJs WebPack example](https://github.com/reactjs/React.NET/tree/master/src/React.Sample.Webpack).

I you get something going do blog about it. Be interested to see the solution.

**Comment by Daniel-Baranowski-BJSS** [comment]
Check this out: https://github.com/aspnet/JavaScriptServices. They mention http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/. It generates an dot net core + react + redux template with server side rendering.

**Comment by JonPSmith** [comment]
Hi @Daniel-Baranowski-BJSS,

Great link! Thanks for sharing that.
