### ISSUE TITLE
Had to modify solution file to load the core project

### ISSUE THREAD

**Issue by luanau** [JonPSmith/AspNetReactSamples#4]
Hi Jon,
Had to change project file name on line 16 of solution file from "ReactWebPack.Core.xproj" to "ReactWebPack.CoreRC2.csproj" for the project to load.
Luan

**Comment by JonPSmith** [comment]
Hi @luanau,

Thanks - that is helpful. Can you send me your new solution file as I am having problems repeating your fix. Thanks.
