### ISSUE TITLE
VS2015 Support

### ISSUE THREAD

**Issue by datasmithtech** [JonPSmith/AspNetReactSamples#7]
Is it possible to you could have a copy of projects in VS2015 format?

I tried opening, and it naturally failed on VS2017 project format.

**Comment by JonPSmith** [comment]
Hi @datasmithtech 

No problem. There is already a branch called `VS2015` which is in Visual Studio 2015 format. 

One thing to note is that Microsoft say that they only support .NET Core projects in VS2017. Yes, the ASP.NET Core version of my project will work in VS2015, but you might run into problems if you try to update it.
